### ISSUE TITLE
Broken again ?

### ISSUE THREAD

**Issue by shubhank008** [buchin/google-image-grabber#12]
Seems its broken again due to some google update ?  
Any and all searches returning blank result (array)

**Comment by juanradark** [comment]
yes, they made a small change yesterday:
![changes](https://user-images.githubusercontent.com/4118403/135716141-537c8207-8955-4605-922b-dfc62752f523.JPG)

**Comment by shubhank008** [comment]
> yes, they made a small change yesterday: ![changes](https://user-images.githubusercontent.com/4118403/135716141-537c8207-8955-4605-922b-dfc62752f523.JPG)

thanks mate

**Comment by buchin** [comment]
solved
