### ISSUE TITLE
demo in test.php file

### ISSUE THREAD

**Issue by drhamied** [buchin/google-image-grabber#8]
Great work.
How can i use it in new file test.php , give me an example how to search image 'apple x' .
I used it as but not work: 
`<?php
require('GoogleImageGrabber.php');
use Buchin\GoogleImageGrabber\GoogleImageGrabber;

$keyword = 'makan nasi';

$images = GoogleImageGrabber::grab($keyword);
?>`

**Comment by buchin** [comment]
What's your error message?

**Comment by Garrettlynch** [comment]
Using similar code to the above and minus installing via composer I have this working but the $images array does not return any results. Something is going wrong in the function grab() right after the response is exploded. There is no item 1 in the $exploded array and I'm guessing the search for ', sideChannel: {}});</script>' will also return nothing as Google has probably changed its code again.

```
		$exploded = explode("AF_initDataCallback({key: 'ds:1', isError:  false , hash: '2', data:", $response);

		$data = isset($exploded[1]) ? $exploded[1] : '';

		$data = explode(', sideChannel: {}});</script>', $data);

		$data = $data[0];

		$data = json_decode($data, true);
```

**Comment by buchin** [comment]
That's because google update. Solved with recent commit.
